//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.10 at 05:50:37 PM CST 
//


package org.agile4j.plugin.gun.xml.servicetype;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}field"/>
 *         &lt;element ref="{}fields"/>
 *       &lt;/choice>
 *       &lt;attribute name="asParm" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="packMode" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fieldOrFields"
})
@XmlRootElement(name = "output")
public class Output {

    @XmlElements({
        @XmlElement(name = "field", type = Field.class),
        @XmlElement(name = "fields", type = Fields.class)
    })
    protected List<Object> fieldOrFields;
    @XmlAttribute(name = "asParm")
    protected Boolean asParm;
    @XmlAttribute(name = "packMode")
    protected Boolean packMode;

    /**
     * Gets the value of the fieldOrFields property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fieldOrFields property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFieldOrFields().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Field }
     * {@link Fields }
     * 
     * 
     */
    public List<Object> getFieldOrFields() {
        if (fieldOrFields == null) {
            fieldOrFields = new ArrayList<Object>();
        }
        return this.fieldOrFields;
    }

    /**
     * Gets the value of the asParm property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAsParm() {
        return asParm;
    }

    /**
     * Sets the value of the asParm property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAsParm(Boolean value) {
        this.asParm = value;
    }

    /**
     * Gets the value of the packMode property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPackMode() {
        return packMode;
    }

    /**
     * Sets the value of the packMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPackMode(Boolean value) {
        this.packMode = value;
    }

}
