//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.14 at 11:23:31 PM CST 
//


package org.agile4j.plugin.gun.xml.tbsql;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}fields" minOccurs="0"/>
 *         &lt;element ref="{}dbSequence" minOccurs="0"/>
 *         &lt;element ref="{}odbindexes" minOccurs="0"/>
 *         &lt;element ref="{}indexes" minOccurs="0"/>
 *         &lt;element ref="{}description" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="abstract" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="category" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="changelog" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="extension" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="longname" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="virtual" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fields",
    "dbSequence",
    "odbindexes",
    "indexes",
    "description"
})
@XmlRootElement(name = "table")
public class Table {

    protected Fields fields;
    protected DbSequence dbSequence;
    protected Odbindexes odbindexes;
    protected Indexes indexes;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String description;
    @XmlAttribute(name = "abstract", required = true)
    protected boolean _abstract;
    @XmlAttribute(name = "category", required = true)
    protected String category;
    @XmlAttribute(name = "changelog")
    protected Boolean changelog;
    @XmlAttribute(name = "extension", required = true)
    protected String extension;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "longname", required = true)
    protected String longname;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "virtual", required = true)
    protected boolean virtual;

    /**
     * Gets the value of the fields property.
     * 
     * @return
     *     possible object is
     *     {@link Fields }
     *     
     */
    public Fields getFields() {
        return fields;
    }

    /**
     * Sets the value of the fields property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fields }
     *     
     */
    public void setFields(Fields value) {
        this.fields = value;
    }

    /**
     * Gets the value of the dbSequence property.
     * 
     * @return
     *     possible object is
     *     {@link DbSequence }
     *     
     */
    public DbSequence getDbSequence() {
        return dbSequence;
    }

    /**
     * Sets the value of the dbSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbSequence }
     *     
     */
    public void setDbSequence(DbSequence value) {
        this.dbSequence = value;
    }

    /**
     * Gets the value of the odbindexes property.
     * 
     * @return
     *     possible object is
     *     {@link Odbindexes }
     *     
     */
    public Odbindexes getOdbindexes() {
        return odbindexes;
    }

    /**
     * Sets the value of the odbindexes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Odbindexes }
     *     
     */
    public void setOdbindexes(Odbindexes value) {
        this.odbindexes = value;
    }

    /**
     * Gets the value of the indexes property.
     * 
     * @return
     *     possible object is
     *     {@link Indexes }
     *     
     */
    public Indexes getIndexes() {
        return indexes;
    }

    /**
     * Sets the value of the indexes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Indexes }
     *     
     */
    public void setIndexes(Indexes value) {
        this.indexes = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the abstract property.
     * 
     */
    public boolean isAbstract() {
        return _abstract;
    }

    /**
     * Sets the value of the abstract property.
     * 
     */
    public void setAbstract(boolean value) {
        this._abstract = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the changelog property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isChangelog() {
        return changelog;
    }

    /**
     * Sets the value of the changelog property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setChangelog(Boolean value) {
        this.changelog = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtension(String value) {
        this.extension = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the longname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongname() {
        return longname;
    }

    /**
     * Sets the value of the longname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongname(String value) {
        this.longname = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the virtual property.
     * 
     */
    public boolean isVirtual() {
        return virtual;
    }

    /**
     * Sets the value of the virtual property.
     * 
     */
    public void setVirtual(boolean value) {
        this.virtual = value;
    }

}
