//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.13 at 01:28:55 PM CST 
//


package org.agile4j.plugin.gun.xml.namesql;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element ref="{}parameterMap"/>
 *         &lt;element ref="{}resultMap"/>
 *         &lt;element ref="{}dynamicSql"/>
 *       &lt;/sequence>
 *       &lt;attribute name="cache" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="longname" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="method" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "parameterMap",
    "resultMap",
    "dynamicSql"
})
@XmlRootElement(name = "dynamicSelect")
public class DynamicSelect {

    protected ParameterMap parameterMap;
    protected ResultMap resultMap;
    protected DynamicSql dynamicSql;
    @XmlAttribute(name = "cache")
    protected String cache;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "longname")
    protected String longname;
    @XmlAttribute(name = "method")
    protected String method;
    @XmlAttribute(name = "type")
    protected String type;

    /**
     * Gets the value of the parameterMap property.
     * 
     * @return
     *     possible object is
     *     {@link ParameterMap }
     *     
     */
    public ParameterMap getParameterMap() {
        return parameterMap;
    }

    /**
     * Sets the value of the parameterMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParameterMap }
     *     
     */
    public void setParameterMap(ParameterMap value) {
        this.parameterMap = value;
    }

    /**
     * Gets the value of the resultMap property.
     * 
     * @return
     *     possible object is
     *     {@link ResultMap }
     *     
     */
    public ResultMap getResultMap() {
        return resultMap;
    }

    /**
     * Sets the value of the resultMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultMap }
     *     
     */
    public void setResultMap(ResultMap value) {
        this.resultMap = value;
    }

    /**
     * Gets the value of the dynamicSql property.
     * 
     * @return
     *     possible object is
     *     {@link DynamicSql }
     *     
     */
    public DynamicSql getDynamicSql() {
        return dynamicSql;
    }

    /**
     * Sets the value of the dynamicSql property.
     * 
     * @param value
     *     allowed object is
     *     {@link DynamicSql }
     *     
     */
    public void setDynamicSql(DynamicSql value) {
        this.dynamicSql = value;
    }

    /**
     * Gets the value of the cache property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCache() {
        return cache;
    }

    /**
     * Sets the value of the cache property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCache(String value) {
        this.cache = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the longname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongname() {
        return longname;
    }

    /**
     * Sets the value of the longname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongname(String value) {
        this.longname = value;
    }

    /**
     * Gets the value of the method property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethod() {
        return method;
    }

    /**
     * Sets the value of the method property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethod(String value) {
        this.method = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
